# Generated by Django 2.0.3 on 2018-04-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMPPContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1023, verbose_name='username')),
                ('contact', models.CharField(max_length=2047, verbose_name='contact')),
                ('in_roster', models.BooleanField(default=False, verbose_name='in roster')),
                ('name', models.CharField(blank=True, max_length=1023, verbose_name='name')),
                ('subscribed_from', models.BooleanField(default=False, verbose_name='subscribed from')),
                ('subscribed_to', models.BooleanField(default=False, verbose_name='subscribed to')),
                ('preapproved', models.BooleanField(default=False, verbose_name='pre-approved')),
                ('pending_in', models.DateTimeField(blank=True, null=True, verbose_name='pending-in')),
                ('pending_out', models.DateTimeField(blank=True, null=True, verbose_name='pending-out')),
                ('groups', models.TextField(blank=True, verbose_name='groups')),
                ('stanza_in', models.TextField(blank=True, verbose_name='pending-in stanza')),
                ('stanza_out', models.TextField(blank=True, verbose_name='pending-out stanza')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='xmppcontact',
            unique_together={('username', 'contact')},
        ),
    ]
